version: "3.8"

services:
  web:
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
  db:
    restart: always
    image: postgres:latest
    container_name: hello_pg
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db-data:
